WebApp/WebApp/Controllers/ChildRecordsController.cs
using FTCWebApp.Caching;
using FTCWebApp.Classes;
using FTCWebApp.DataModels;
using FTCWebApp.ServiceReference1;
using FTCWebApp.ViewModels;
using FTCWebApp.ViewModels.GUI_Pieces;
using log4net;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace FTCWebApp.Controllers
{
    public class ChildRecordsController : Controller
    {

        // private FieldServicesClient _svc = new FieldServicesClient("BasicHttpsBinding_IFieldServices");

        private DAL.API_EndPointer api_endpointer = new DAL.API_EndPointer();

        // private FieldServicesClient _svc = new FieldServicesClient("BasicHttpBinding_IFieldServices");
        private static readonly ILog log = LogManager.GetLogger(typeof(ChildRecordsController));

        // GET: ChildRecords
        public ActionResult Index()
        {
            UserInfo uInfo = SessionManager.Get<UserInfo>("UserInfo");
            if (uInfo == null)
            {
                return RedirectToAction("SessionReset", "Home");
            }

            ChildRecordsVM model = new ChildRecordsVM(Classes.User_Session_Defaults.enum_Display_Page.Child_Records, Session);
            model.currentUser = uInfo;

            return View("ChildRecords", model);
        }

        //Summary
        //Get the list of child records pending for Update 
        [HttpPost]
        public string getChildRecordData(string countryID, string locationID)
        {
            try
            {
                UserInfo _currentUser = SessionManager.Get<UserInfo>("UserInfo");

                if (countryID.ToLower() == "null")
                    countryID = string.Empty;

                if (locationID.ToLower() == "null")
                    locationID = string.Empty;


                User_Session_Defaults.Set_User_Preferred_Location_Code_ID_Session_Var(Session, locationID);

                User_Session_Defaults.Set_User_Preferred_Country_Session_Var(Session, countryID);



                int _countryID = String.IsNullOrEmpty(countryID) ? 0 : Convert.ToInt32(countryID);
                int _locationID = String.IsNullOrEmpty(locationID) ? 0 : Convert.ToInt32(locationID);

                var Incompleteupdates = new ListChild[2];
                Incompleteupdates = api_endpointer.svc.GetChildRecords(_currentUser.ID.ToString(), _countryID, _locationID);
                return JsonConvert.SerializeObject(Incompleteupdates);
            }
            catch (Exception ex)
            {
                log.Debug("Failed to get the Child Records!", ex);
                return null;
            }
        }


        /*
        [HttpPost]
        public string getUserCountryDatum(string UserID)
        {

            string UserCountryDatum = "";

            try
            {

                Country_DropDown_Item[] country_select_items = api_endpointer.svc.GetCountryRecords(UserID);

                UserCountryDatum = JsonConvert.SerializeObject(country_select_items);

            }
            catch (Exception ex)
            {

                UserCountryDatum = JsonConvert.SerializeObject(ex);

            }

            return UserCountryDatum;

        }
        */


    }
}

WebApp/WebApp/Controllers/PanMainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Web.Mvc;
using FTCWebApp.DataModels;
using FTCWebApp.ViewModels;
using FTCWebApp.Caching;
using System.Collections.Specialized;
using FTCWebApp.ServiceReference1;
using FTCWebApp.Validation;
using FTCWebApp.Utillities;
using Newtonsoft.Json;
using log4net;
using System.Drawing;


using FTCWebApp.Classes;


namespace FTCWebApp.Controllers
{
    public class PanMainController : Controller
    {
        private FieldServicesClient _svc;
        private EnrollmentValidation _val;
        private EnrollUtil _util;
        private static readonly ILog log = LogManager.GetLogger(typeof(PanMainController));

        public PanMainController()
        {
            _svc = new FieldServicesClient("BasicHttpsBinding_IFieldServices");
            _val = new EnrollmentValidation();
            _util = new EnrollUtil();
        }

        // Controller for Enrollment Page view 
        public ActionResult Enrollment(string user_info)
        {
            UserInfo uInfo = SessionManager.Get<UserInfo>("UserInfo");
            if (uInfo == null)
            {
                return RedirectToAction("SessionReset", "Home");
            }

            var enrollment = new CommonVM();
            enrollment.currentUser = uInfo;
            enrollment.Declines = new List<DeclineDetails>();

            //Remove all previous user files or data stored in Session
            Session.RemoveAll();
            SessionManager.Set<UserInfo>("UserInfo", enrollment.currentUser);

            ViewBag.Module = "Enrollment";

            enrollment.child = new Child();
            enrollment.Declines = new List<DeclineDetails>();
            enrollment.child.NumberOfBrothers = enrollment.child.NumberOfSisters = 0;

            log.Debug("Leaving Enrollment");
            return View(enrollment);
        }

        public ActionResult EnrollmentWorklist()
        {
            
            UserInfo uInfo = SessionManager.Get<UserInfo>("UserInfo");
            if (uInfo == null)
            {
                return RedirectToAction("SessionReset", "Home");
            }

            var model = new CommonVM(User_Session_Defaults.enum_Display_Page.Enrollment, Session);

            model.currentUser = uInfo;
            model.Declines = new List<DeclineDetails>();
            
            Dictionary<string, object> dct_User_Defaults = Classes.User_Session_Defaults.Get_User_Defaults(Session);
            
            //Remove all previous user files or data stored in Session
            Session.RemoveAll();
            SessionManager.Set<UserInfo>("UserInfo", model.currentUser);

            model.user_Session_Defaults.Add_Dictionary_Items_To_Session(Session, dct_User_Defaults);


            ViewBag.Module = "Enrollment";

            log.Debug("Leaving Enrollment Worklist");
            return View(model);
        }

        //Summary
        //Get the list of child records pending for Update 
        [HttpPost]
        public string getEnrollmentWorklist(string countryID, string locationID, string actionTypeID)
        {
            try
            {

                Set_Enrollment_Page_User_Defaults(countryID, locationID, actionTypeID);


                var uInfo = SessionManager.Get<UserInfo>("UserInfo");
                var IncompleteEnrollments = new ListChild[2];

                //if action id is create bring every record from the enrollment table
                IncompleteEnrollments = _svc.GetIncompleteEnrollments(uInfo.ToString(), Helper.ParseInt(countryID), Helper.ParseInt(locationID), 0);
                var GenderValues = CacheManager.GetFromCache<List<SelectListItem>>("Gender");
                foreach (var record in IncompleteEnrollments)
                {
                    var code = GenderValues.FirstOrDefault(a => a.Value == record.Gender);
                    if (code != null)
                    {
                        record.Gender = code.Text;
                        if (!String.IsNullOrEmpty(record.Gender))
                        {
                            record.Gender = record.Gender.Substring(0, 1);
                        }
                    }
                }
                return JsonConvert.SerializeObject(IncompleteEnrollments);
            }
            catch (Exception ex)
            {
                log.Debug("Failed to get the Incomplete child updates !", ex);
                return null;
            }
        }


        private void Set_Enrollment_Page_User_Defaults(string countryID, string locationID, string actionTypeID)
        {

            // SET USER DEFAULT VALUES
            Classes.User_Session_Defaults.Set_User_Preferred_Country_Session_Var(Session, countryID);

            Classes.User_Session_Defaults.Set_User_Preferred_Location_Code_ID_Session_Var(Session, locationID);

            Classes.User_Session_Defaults.Set_User_Preferred_Enrollment_Action_Type_Session_Var(Session, actionTypeID);

        }


        public ActionResult LoadEnrollmentChild(string id)
        {
            ViewBag.Module = "Enrollment";
            var model = _util.setupIncompleteEnrollmentView(id);
            return View("Enrollment", model);
        }

        //Summary
        //Get the Location Names and Location Codes upon selection of Country by the user
        public JsonResult GetLocationsByCountry(int id)
        {
            List<SelectListItem>[] LocationListArray = _util.GetLocationsByCountry(id);

            if (LocationListArray != null)
            {
                var LocationNames = LocationListArray.AsEnumerable();
                return Json(LocationNames, JsonRequestBehavior.AllowGet);
            }
            else
                return null;
        }

        //Get the decline sub reason for a selected workflow/ decline type and if translation is required for the step
        public string GetWorkflowStepDetails(string id)
        {
            try
            {
                var DeclineSubReasonList = (CacheManager.GetFromCache<List<Tuple<string, string, string>>>("Decline_SubReason"));
                var WorkflowStepList = CacheManager.GetFromCache<List<WorkflowStepModel>>("Step").ToList();

                // list of subcategory for a given category of decline 
                var SubDeclines = DeclineSubReasonList.Where(a => a.Item2 == id);
                var DeclineSubReason = new List<SelectListItem>();
                var TranslationDefault = WorkflowStepList.FirstOrDefault(a => a.Description == id).TranslationRequired;

                foreach (var item in SubDeclines)
                {
                    DeclineSubReason.Add(new SelectListItem { Value = item.Item3, Text = item.Item3 });
                }

                var Declines = DeclineSubReason.AsEnumerable();
                var data = new { Success = true, Declines = Declines, TranslationDefault = TranslationDefault };
                return JsonConvert.SerializeObject(data);
            }
            catch (Exception ex)
            {
                log.Debug("Failed to get the Decline sub categories !", ex);
                return null;
            }
        }

        //Summary
        //Populate some of the Enrollment Information dropdown options dynamically depending on the data of birth set by the user
        public JsonResult GetFieldData(string age)
        {
            try
            {
                if (!string.IsNullOrEmpty(age))
                {
                    int Age = Convert.ToInt32(age);
                    var Fieldset = _util.GetFieldData(Age).AsEnumerable();
                    return Json(Fieldset, JsonRequestBehavior.AllowGet);
                }
                else
                { return null; }
            }
            catch (Exception ex)
            {
                log.Debug("Failed to get the field data for the selected age !", ex);
                return null;
            }
        }

        //Summary
        //This method takes an enrollment file and stores in the session
        [HttpPost]
        public string UploadAFile(HttpPostedFileBase file, string ChildID, string ContentTypeID, string ImgCropArea_X1, string ImgCropArea_Y1, string ImgCropArea_Width, string ImgCropArea_Height, string Module = null)
        {
            try
            {

                var fileUpload_ready = _util.AddFileData(file, ChildID, ContentTypeID, ImgCropArea_X1, ImgCropArea_Y1, ImgCropArea_Width, ImgCropArea_Height);

                object data = null;

                data = _util.processUploadFile(file, ChildID, ContentTypeID, fileUpload_ready);

                return JsonConvert.SerializeObject(data);
            }
            catch (Exception ex)
            {
                log.Debug("Failed to upload the file !", ex);
                return null;
            }
        }

        //This method is used to pass the Translated MLE to the API and DB
        public string GetMLETranslationImage(FormCollection formData)
        {
            try
            {
                UploadFile file = new UploadFile();

                var FilePath = System.Web.HttpContext.Current.Server.MapPath("~/Content/doc.jpg");
                Image image = Image.FromFile(FilePath);
                EnrollUtil util = new EnrollUtil();
                file.FileBytes = (byte[])(new ImageConverter()).ConvertTo(image.Clone(), typeof(byte[]));
                file.FileName = "Major Life Event";
                //Image image = null;
                //using (MemoryStream mStream = new MemoryStream(file.FileBytes))
                //{
                //    image = Image.FromStream(mStream);
                //}
                var bytestring = util.createThumbnail(image);
                var data = new { Success = true, Image = bytestring, contenttype = "MLE", Id = "MLETranslation", Name = file.FileName, Message = Helper.MessageWithDateTimeAdded("MLE Translation has been uploaded!") };

WebApp/WebApp/Views/ChildRecords/ChildRecords.cshtml
@{
    ViewBag.Title = "Child Records";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model FTCWebApp.ViewModels.ChildRecordsVM

<script>
    $(function () {
        var firstClick = true;
        $("#getChildRecords").click(function () {
            // Construct data string
            var formData = new FormData();
            formData.append('countryID', $('#child_CountryId').val());
            formData.append('locationID', $('#child_LocationCodeID').val());
            $.ajax({
                type: 'POST',
                url: '@Url.Action("getChildRecordData", "ChildRecords")',
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    if (!firstClick) {
                        $.jgrid.gridUnload('#ChildRecords_tableGrid');
                    }
                    firstClick = false;
                    $("#ChildRecords_tableGrid").jqGrid({
                        datatype: 'jsonstring',
                        datastr: data,
                        jsonReader: {
                            root: "data",
                            ID: "ChildID",
                            Number: "ChildNumber"
                        },
                        colModel: [
                            { label: 'Child ID', name: 'ChildID', key: true, width: 300, jsonmap: "ChildID", hidden: true, search: false },
                            {
                                label: 'Child Number', name: 'ChildNumber', width: 120, align: 'center', jsonmap: "ChildNumber", search: true, formatter: function (cellvalue, options, rowObject) {
                                    var x = '@Html.ActionLink("ChildNumber", "LoadChildRecord", "PanMain", new { id = "ChildID" }, new { @style = "color:Blue;font-weight:bold;" })';
                                    // replace string "ChildNumber" with the child number
                                    var y = x.replace("ChildNumber", rowObject.ChildNumber);
                                    // replace string "ChildID" with the child ID
                                    return y.replace("ChildID", rowObject.ChildID);
                                }
                            },
                            { label: 'First Name', name: 'FirstName', width: 120, sortable: true, jsonmap: "FirstName", search: false },
                            { label: 'Middle Name', name: 'MiddleName', width: 130, sortable: true, jsonmap: "MiddleName", search: false },
                            { label: 'Last Name', name: 'LastName', width: 200, sortable: true, jsonmap: "LastName", search: false },
                            { label: 'Other Name', name: 'OptionalName', width: 100, sortable: true, jsonmap: "OptionalName", search: false },
                            { label: 'Date of Birth', name: 'DateOfBirth', width: 130, align: 'right', sortable: true, jsonmap: "DateOfBirth", formatter: 'date', search: false },
                            { label: 'Gender', name: 'Gender', width: 100, sortable: true, jsonmap: "Gender", search: false },
                            { label: 'Location Name', name: 'Location', width: 200, sortable: true, jsonmap: "Location", search: false }
                        ],
                        height: 'auto',
                        width: 'auto',
                        loadonce: false,
                        rowNum: 15,
                        gridview: true,
                        viewrecords: true,
                        sortorder: "desc",
                        rowList: [10, 15, 20],
                        pager: '#ChildRecords_Pager',
                        //Commented for future use
                        //sortname: 'Location',
                        pgbuttons: true
                    }).jqGrid('filterToolbar', { stringResult: true, searchOnEnter: false, defaultSearch: "cn" });
                    $('#lui_ChildRecords_tableGrid').removeClass('ui-widget-overlay jqgrid-overlay');
                }
            });
        });


        @{ 

            Html.RenderPartial("~/Views/partials/pv_User_Cache_Defaults.cshtml", Model.user_Session_Defaults);
                                   

        }

       
    });
</script>
<body>
    <!-- Update index page -->
    <div id="content" style="position:relative; padding-top:30px">
        <div class="col-xs-12 colsm-12 col-md-12 col-xl-12">
            <div class="col-xs-12 colsm-12 col-md-3 col-xl-3" style="padding-left:0px;">
                <div class="editor-label" style="padding-left:0px;">
                    <div>
                        @Html.LabelFor(model => model.child.CountryId)
                    </div>
                </div>
                <div class="editor-field childform" style="padding-left:0px;">
                    @Html.DropDownListFor(model => model.child.CountryId, new SelectList(Model.Countries, "Value", "Text"), "Select Country", new { @class = "form-control", style = "width: 100%;" })
                </div>
            </div>
            <div class="col-xs-12 colsm-12 col-md-3 col-xl-3">
                <div class="editor-label">
                    <div>
                        @Html.LabelFor(model => model.child.LocationName)
                    </div>
                </div>
                <div class="editor-field childform">
                    @Html.DropDownListFor(model => model.child.LocationName, Enumerable.Empty<SelectListItem>(), "Select Location", new { @class = "form-control", style = "width: 100%;" })
                </div>

            </div>
            <div class="col-xs-12 colsm-12 col-md-3 col-xl-3">
                <div class="editor-label">
                    <div>
                        @Html.LabelFor(model => model.child.LocationCodeID)
                    </div>
                </div>
                <div class="editor-field childform">
                    @Html.DropDownListFor(model => model.child.LocationCodeID, Enumerable.Empty<SelectListItem>(), "Select Location Code", new { @class = "form-control", style = "width: 100%;" })
                </div>
            </div>
        </div>
        <div class="col-xs-12 colsm-12 col-md-12 col-xl-12">
            <div class="col-xs-12 colsm-12 col-md-3 col-xl-3" style="padding-left:0px;">
                <input type="button" value="Submit" id="getChildRecords" style="width:70%; background-color:orange;" class="form-control font-weight-bold" />
            </div>
        </div>
        <div class="col-xs-12 colsm-12 col-md-12 col-xl-12">
            <div style="margin-top:10px;">
                <table id="ChildRecords_tableGrid"></table>
                <div id="ChildRecords_Pager"></div>
            </div>
        </div>
    </div>
</body>